Repository ormcamp-fe-3rd/space-var, pull requests merged in 2024-11, with the labels that each got.

#3 [지윤환]추가 - start 레이아웃 및 버튼디자인
  pages/start.html
Labels: enhancement

#2 [박정혜]추가 : company sec3~5 작업
  assets/fonts/Pretendard-Black.otf
  assets/fonts/Pretendard-Black.woff2
  assets/fonts/Pretendard-Bold.woff2
  assets/fonts/Pretendard-ExtraBold.woff2
  assets/fonts/Pretendard-ExtraLight.woff2
  assets/fonts/Pretendard-Light.woff2
  assets/fonts/Pretendard-Medium.otf
  assets/fonts/Pretendard-Medium.woff2
  assets/fonts/Pretendard-Regular.woff2
  assets/fonts/Pretendard-SemiBold.otf
  assets/fonts/Pretendard-SemiBold.woff2
  assets/fonts/ZenDots-Regular.woff2
  assets/images/company/bg_sec5.png
  assets/images/company/pic_crews1.png
  assets/images/company/pic_crews1.svg
  assets/images/company/pic_crews2.png
  assets/images/company/pic_crews3.png
  assets/images/company/pic_crews4.png
  assets/styles/common.css
  assets/styles/company.css
  pages/company.html
Labels: enhancement

#1 [신명희] - 추가:book.html form 레이아웃
  pages/book.html
Labels: enhancement

#4 [김수진]수정:Company page 상단(레이아웃과 배경 border 그림자 구현)
  .gitignore
  assets/images/left-btn.png
  assets/images/right-btn.png
  assets/images/solar1.png
  assets/images/solar2.png
  assets/images/solar4.png
  assets/images/solar5.png
  assets/images/solar6.png
  assets/images/solar8.png
  assets/images/space12.jpg
  assets/styles/common.css
  assets/styles/company.css
  js/company.js
  package-lock.json
  package.json
  pages/company.html
  planet/file.png
  planet/금성.jpg
  planet/달.jpg
  planet/목성.jpg
  planet/천왕성-removebg-preview.png
  planet/천왕성.jpg
  planet/토성.jpg
  planet/해왕성.jpg
  planet/화성.jpg
Labels: enhancement

#6 [박정혜]수정: company conflict 수정
  assets/styles/common.css
  assets/styles/company.css
  js/company.js
  package-lock.json
  package.json
  pages/company.html
Labels: enhancement

#7 [박정혜]수정: prettier 제거
  .gitignore
  package-lock.json
  package.json
  pages/company.html
Labels: bug

#8 [김민섭]추가 - carousel 애니메이션 구현
  .gitignore
  assets/fonts/Pretendard-Black.otf
  assets/fonts/Pretendard-Black.woff2
  assets/fonts/Pretendard-Bold.woff2
  assets/fonts/Pretendard-ExtraBold.woff2
  assets/fonts/Pretendard-ExtraLight.woff2
  assets/fonts/Pretendard-Light.woff2
  assets/fonts/Pretendard-Medium.otf
  assets/fonts/Pretendard-Medium.woff2
  assets/fonts/Pretendard-Regular.woff2
  assets/fonts/Pretendard-SemiBold.otf
  assets/fonts/Pretendard-SemiBold.woff2
  assets/fonts/ZenDots-Regular.woff2
  assets/images/company/bg_sec5.png
  assets/images/company/pic_crews1.png
  assets/images/company/pic_crews1.svg
  assets/images/company/pic_crews2.png
  assets/images/company/pic_crews3.png
  assets/images/company/pic_crews4.png
  assets/images/left-btn.png
  assets/images/right-btn.png
  assets/images/solar1.png
  assets/images/solar2.png
  assets/images/solar4.png
  assets/images/solar5.png
  assets/images/solar6.png
  assets/images/solar8.png
  assets/images/space12.jpg
  assets/styles/book.css
  assets/styles/common.css
  assets/styles/company.css
  js/book.js
  js/company.js
  pages/book.html
  pages/company.html
  planet/file.png
  planet/금성.jpg
  planet/달.jpg
  planet/목성.jpg
  planet/천왕성-removebg-preview.png
  planet/천왕성.jpg
  planet/토성.jpg
  planet/해왕성.jpg
  planet/화성.jpg
Labels: enhancement

#9 [신명희] Book - form 전체적으로 스타일 완성
  assets/images/book/form/jcb.svg
  assets/images/book/form/mastercard.svg
  assets/images/book/form/visa.svg
  assets/styles/book.css
  assets/styles/common.css
  pages/book.html
Labels: enhancement

#10 [신명희]수정: form위치 content div 안으로 이동
  assets/styles/book.css
  pages/book.html
Labels: invalid

#12 [신명희]추가: 폼 검증(input, checkbox)
  assets/styles/book.css
  js/book.js
  pages/book.html
Labels: enhancement

#14 [신명희]추가:side-bar
  js/book.js
  pages/book.html
Labels: bug

#15 [신명희]수정: 자잘한 여백 정리
  assets/styles/book.css
  pages/book.html
Labels: bug, enhancement

#16 [김민섭]추가: font url 추가
  assets/styles/book.css
Labels: enhancement

#17 [박정혜] 좌석선택 페이지 작업완료
  assets/images/seats/pic_spaceship.png
  assets/styles/common.css
  assets/styles/seats.css
  js/seats.js
  pages/seats.html
Labels: enhancement

#18 [박정혜]수정: seats.js 펼치기 기능 오류수정
  js/seats.js
Labels: enhancement

#21 [김민섭]수정: carousel planet 위치 및 애니메이션 변경, 변수명 정리
  assets/styles/book.css
  js/book.js
  pages/book.html
Labels: enhancement

#22 [신명희] book-modal 구현
  assets/images/ticket/qr.png
  assets/styles/book.css
  js/book.js
  pages/book.html
Labels: enhancement

#23 [신명희]수정: planet 이름 받아오는 변수명
  js/book.js
Labels: bug

#42 [박정혜] 수정 : 시맨틱 태그 추가, 행성소개 가운데 정렬
  assets/styles/company.css
  pages/company.html
Labels: enhancement

#43 [박정혜]수정: 로고 링크추가, 헤더 왼쪽버튼 이름 수정
  assets/styles/company.css
  pages/company.html
Labels: enhancement

#39 [김민섭]수정: book logo 클릭시 start 페이지로 이동
  assets/images/book/planet/surface/Jupiter.svg
  assets/images/book/planet/surface/Mars.svg
  assets/images/book/planet/surface/Mercurius.svg
  assets/images/book/planet/surface/Neptune.svg
  assets/images/book/planet/surface/Pluto.svg
  assets/images/book/planet/surface/Saturn.svg
  assets/images/book/planet/surface/Uranus.svg
  assets/images/book/planet/surface/Venus.svg
  assets/styles/book.css
  js/book.js
  pages/book.html
Labels: enhancement

#49 [신명희]수정: 중복되는 클래스명, border-radius 적용
  assets/styles/book.css
  js/book.js
  pages/book.html
Labels: bug

#52 [박정혜] company -> main으로 병합
  .gitignore
  assets/images/facebook.png
  assets/images/instagram.png
  assets/styles/company.css
  js/company.js
  pages/company.html
  planet/file.png
  planet/금성.jpg
  planet/달.jpg
  planet/목성.jpg
  planet/천왕성-removebg-preview.png
  planet/천왕성.jpg
  planet/토성.jpg
  planet/해왕성.jpg
  planet/화성.jpg
Labels: enhancement

#59 [박정혜]수정: book now 링크 수정
  assets/styles/common.css
  assets/styles/company.css
  pages/company.html
Labels: enhancement

#62 [book]footer 추가
  assets/styles/book.css
  js/book.js
  js/seats.js
  pages/book.html
Labels: bug, enhancement

#67 [신명희]삭제:Delete 0_original directory
  0_original/carousel-nomal.css
  0_original/carousel-nomal.html
  0_original/carousel-revolution.css
  0_original/carousel-revolution.html
  0_original/carousel-revolution.js
Labels: bug, invalid

#66 [신명희]삭제:Delete 0_ignore directory
  0_ignore/bubble.css
  0_ignore/bubble.html
  0_ignore/bubble.js
  0_ignore/bubble.map
  0_ignore/bubble.scss
  0_ignore/laser.css
  0_ignore/laser.html
  0_ignore/laser.js
  0_ignore/lasereff.css
  0_ignore/lasereff.html
  0_ignore/lasereff.js
  0_ignore/loading.css
  0_ignore/loading.html
  0_ignore/loading.js
  0_ignore/startpage.css
  0_ignore/startpage.html
  0_ignore/startpage.js
Labels: bug, invalid, wontfix

#68 [신명희]수정: 민섭님 코드 다시 복구
  js/book.js
Labels: bug

#69 [신명희]추가: 선택한 좌석 예매완료 티켓에도 보여주기
  js/book.js
  js/seats.js
Labels: enhancement

#70 [지윤환]start-js파일 주석 설명 추가
  js/start.js
Labels: bug

#72 [박정혜]수정: seats.js 설명주석 추가, seats.css import 추가
  assets/styles/seats.css
  js/seats.js
  pages/seats.html
Labels: documentation

#80 [김민섭] 수정: book.js 설명 주석, side 이미지 애니메이션 추가
  assets/styles/book.css
  js/book.js
Labels: documentation

#82 [신명희] book-form 자잘한 버그 수정 및 ticket exit 버튼 디자인 수정
  assets/styles/book.css
  js/book.js
  pages/book.html
Labels: bug

#91 [김민섭]수정: carousel saturn 위치 변경 및 애니메이션 시간 재설정
  assets/images/book/planet/button/left_btn.svg
  assets/images/book/planet/button/right_btn.svg
  assets/images/book/planet/side/Jupiter_Side.svg
  assets/images/book/planet/side/Mars_Side.svg
  assets/images/book/planet/side/Mercurius_Side.svg
  assets/images/book/planet/side/Neptune_Side.svg
  assets/images/book/planet/side/Pluto_Side.svg
  assets/images/book/planet/side/Saturn_Side.svg
  assets/images/book/planet/side/Uranus_Side.svg
  assets/images/book/planet/side/Venus_Side.svg
  assets/images/book/planet/side/default_Side.svg
  assets/images/book/side-temp.jpg
  assets/styles/book.css
  js/book.js
  pages/book.html
Labels: enhancement

#94 [김수진]수정:entry page(html head 수정,js 주석 추가)
  js/entry.js
  pages/entry.html
Labels: enhancement

#95 [신명희]수정: README.md
  README.md
Labels: documentation

#96 [김민섭]수정: 수성 위치 변경 및 캐러셀 짤림 현상 제거
  assets/styles/book.css
  js/book.js
Labels: bug, enhancement

#98 [박정혜]수정 : company.css, seats.css 수정
  assets/styles/common.css
  assets/styles/company.css
  assets/styles/seats.css
Labels: bug

#99 [박정혜] 추가 : main으로 병합
  assets/styles/common.css
  assets/styles/company.css
  assets/styles/seats.css
Labels: documentation

#100 [김수진]수정:entry page(주석, 코드 가독성 수정)
  assets/styles/entry.css
  js/entry.js
Labels: enhancement

#101 [박정혜]수정: company 행성이름 위치 수정
  assets/styles/company.css
  assets/styles/seats.css
Labels: bug

#102 [지윤환]-start-코드명 수정/메인화면 디자인 반응형 추가
  assets/styles/start.css
  js/start.js
  pages/start.html
Labels: enhancement

#103 [신명희]수정: book-planet 리팩토링 및 버그 수정, book-form 관련 class 생성
  js/book.js
  js/start.js
  js/states/FormState.js
  js/states/ReservationState.js
  pages/book.html
Labels: bug, enhancement

#104 [신명희]수정: book form 리팩토링 및 버그 수정
  js/book.js
  js/states/FormState.js
  js/states/ReservationState.js
  pages/book.html
Labels: bug, enhancement, invalid

#106 [신명희]수정:entry.css
  assets/styles/entry.css
Labels: bug

#109 [신명희]수정: next 버튼에 event.preventDefault() 추가
  js/seats.js
Labels: bug

#110 [신명희]수정: seats 버그 수정, 주석 추가, 안쓰는 company.js 삭제
  js/company.js
  js/seats.js
Labels: bug, invalid

#111 [신명희]수정 index.html js css
  assets/styles/company.css
  assets/styles/index.css
  index.html
  js/book.js
  js/index.js
  js/store/FormState.js
  js/store/ReservationState.js
Labels: invalid

#115 [김수진]수정:불필요한 파일 삭제
  assets/images/company/facebook.png
  assets/images/company/instagram.png
  assets/styles/layout.css
Labels: enhancement

#116 [박정혜]수정 : company.css footer 레이아웃 수정
  assets/styles/company.css
Labels: bug

#119 [신명희] book 접근성 높이기
  assets/js/book.js
  assets/styles/book.css
  pages/book.html
Labels: enhancement

#123 [신명희] submit 버튼 수정, go to main page 버튼 수정
  assets/js/book/book.js
  assets/styles/book/book.css
  pages/book/book.html
Labels: bug

#126 [김민섭]수정: start.js 비디오 및 텍스트 표현 (미완성)
  src/start/start.js
Labels: documentation

#128 [전체수정: event 인수로 사용 최대한 하지 않도록 변경, console.log 삭제
  src/book/book.js
  src/book/util/FormValidator.js
Labels: bug, enhancement

#130 [전체]수정: start 페이지 스크롤 최적화 방식 변경
  src/start/start.css
  src/start/start.html
  src/start/start.js
Labels: bug
